[project]
name = "pympi"
version = "0.1.0"
description = "Simple Python-based MPI implementation"
readme = "README.md"
authors = [
    { name = "Miguel Ãngel Prosper", email = "mprosper@uji.es" }
]
requires-python = ">=3.13"
dependencies = [
    "bidict>=0.23.1",
    "intbitset>=4.0.0",
    "net-queue>=0.1.0"
]
